from Bio.Seq import Seq
import primer3
import re
import json
# import numpy as np
# import prc_lib as plib
# # snp = 'ATGCAATTGGCCAAATTTGGGCCCAAAATTTTGGGGCCCCAAAAATTTTTGGGGGCCCCCAAAAAATTTTTTGGGGGGCCCCCC'
# print(primer3.bindings.calc_hairpin('AAAATAACTTCAATTCTACACAGTACGTGTC'))
# with open('clean_primer_samples.txt', 'w') as output:
#     with open("primer_samples.txt", "r") as input:
#         for line in input:
#             seq = json.loads(line)
#             if re.match(r'^[ATCGatcg]$' ,seq['allele']) and re.match(r'^[ATCGatcg]+$' ,seq['sequence']):
#                 output.write(f"{str(seq)}\n")


for i in range(10):
    print(i+1)

    # snp_df = []
    # with open('clean_primer_samples.txt', 'r') as output:
    #     for line in output:
    #         seq = json.loads(line)
    #         snp_df.append(seq)



# snp = 'ABCDEFGHIJKLmNOPQRSTUVWXYZ'
# pessimism = 5
# start = 0
# middle = 13
# max_dist = 12
# min_dist = 2
# # for i in range (3):
# #     for length in range(10):
# # trimmed = snp[middle+min_dist:middle+max_dist]
# # print(trimmed)
# # start += 1
# # print("try again")
#     # print(length)
# myString = "Cot"

# print (myString)
# myString = myString[:1] + "A" + myString[2:]
# print (myString)

# snp_data = [{'snpID': 'rs1799971', 'allele': 'A', 'sequence': 'TCCTGGGTCAACTTGTCCCACTTAGATGGCAACCTGTCCGACCCATGCGGTCCGAACCGCA', 'position': 30}, 
#             {'snpID': 'rs1799971', 'allele': 'G', 'sequence': 'TCCTGGGTCAACTTGTCCCACTTAGATGGCGACCTGTCCGACCCATGCGGTCCGAACCGCA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'G', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCGACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'A', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCAACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'C', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCCACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'T', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCTACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}]

# snp_short = snp[0:10]
# print(f"Normal string: {snp_short}")
# seq = Seq.Seq(snp_short)
# print(f"Now a sequence in BIO Python: {seq}")
# reverse = seq.reverse_complement()
# print(f"Now a reverse sequence in Bio Python: {reverse}")
# rev_string = str(reverse)
# print(f"Now a string again: {rev_string}")
# reverse

# np_frame = np.array(snp_data)

# for i in np_frame:
#     print(i['sequence'])
# plib.generate_allele_specific_primers(snp_data, 24, 26)
# test = "TCCTGGGTCAACTTGTCCCACTTANATGGCYACCTGNCCGACCCATGCGGTCCGAACCGCA"
# print(test[30+7:])
# print(test[:30+1-6])# the end is exclusive 
# print(test[-(6+2):-(0)])# the end is exclusive 
# reverse_test = str(Seq(test[30+7:]).reverse_complement())
# print(reverse_test)

# results =
# YACCTGNCCGACCCATGCGGTCCGAACCGCA
# TCCTGGGTCAACTTGTCCCACTTANATGGCY

# CCGACCCATGCGGTCCGAACCGCA
# TGCGGTTCGGACCGCATGGGTCGG
# inverted and spun around
{'snpID': 'rs2977670', 'allele': 'T', 'primer_sequence': 'GGACCTATTGCTTAAGGTGGGT', 'direction': 'forward', 'length': 22, 'tm': 59.758569657346015, 'gc_content': 0.5, 
'hairpin': ThermoResult(structure_found=True, tm=46.22, dg=-739.31, dh=-25600.00, ds=-80.16), 'homomdimer': ThermoResult(structure_found=True, tm=4.29, dg=-4565.16, dh=-56400.00, ds=-167.13), 'tm_score': 0.24143034265398455, 'gc_score': 49.5, 'score': 49.741430342653985}

{'snpID': 'rs2977670', 'allele': 'T', 'primer_sequence': 'TTCCGTTCTATTCCATTCTAGTCC', 'direction': 'forward', 'length': 24, 'tm': 57.84197746874719, 'gc_content': 0.4166666666666667, 'hairpin': ThermoResult(structure_found=False, tm=0.00, dg=0.00, dh=0.00, ds=0.00), 'homomdimer': ThermoResult(structure_found=True, tm=-19.22, dg=-2493.09, dh=-39400.00, ds=-119.00), 'tm_score': 2.1580225312528114, 'gc_score': 49.583333333333336, 'score': 51.74135586458615}


# snp_df = [{'snpID': 'rs28454925', 'allele': 'C', 'sequence': 'ATCGACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGCAATGGAATCGAATGGGATGGAATGTATTGGAATGGACTCGAATGGCATGGACAGGAGTGGACCCGAATGAAATGGAATGGAATGGAATGGTCTCGAGTGGAATGGGATGGGATGGGATGGGATGCGATGGGATGGGATGGGATGGGATGGGATGGGATGGGATGGATTTGAATGGAATAGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATAGACTCGAAAGGATTGGAATGGAATGGACTCGAATGGAATGGAATGGACATGAATGGAACGGAATGGAATGGAATGAACTCGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATGCAATGGAATGGACTCGAATGGAATGGAATGGAATTGACTCAGATGGAATGGAATGGAATGGACTCGAAAGGATTGGAATGGAATACAATGGAATGGTCTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGACTGCAATGGAATGGACTCAAATGGAATGGAATGGAACTGACTCGAATGGAATTGAATGGAATGGACCCGAATGGAATGGAATGGACTGGGCTCAAATGGAATGGAATGGAAAAGAATGGAATGGAATAGAATGGACTGGAATGTAATGAGTTTGGAATGGACTTGAATGCAATGGAATGGAATGGAATGGAATGGAATGGACTCAAATGGAATAGCATGGAATGGAATGGACTCAAATGCATTGGAATGGAATGGACTCGAATGGAATGGAATGGACTCGAATGGAATGGAGTTGAATGGACTCATATGGAATGGAATGGCATTGAATGGACTCGAATGGAATAGAATTATAACAGAATGGAATGAACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGAAAGGTGCTCGAATAGAATGGAATGGAATGGAATAGAATGGACTCAAATGGAATGGAATATAATGGAATGGGAATGGGAATGGGAATGGAAGGGATGGGATGGGATGGGATGTAATGGAATGGAATGCAATGGAATGGACACCTATGGAATGCAGTTGAATTGAATGGACCCGAAAGCAATGGAATGGAATGCAATGTACTCGAATGGAATGGACTCGAATGGAATGGAATGAACTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAATGGAATGCACCCAAATGGAATTAAATGTAATGGAATGGACTTGAATGAAATGGCAAGAATGGACTCGAATGGAATGGAATGGAATGGAATCGAATGGAATCGAATGGAATGACATGGAATGGATTCGAATGGAAAGACATGGAATGGACTCGATTGGAATGGGTTGGGATGGAATGATCTAGAATGTAATGGAATGGAATGGACTCAAATGGAATAGAATGGAATAGAATGGACTCGAATATAATGGAATGAAATTGGCTCGAATGGAATGGAATGGACTTGAATGGAATGGAATGGAATCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAAAGGAATGGACTCAAATGGAATAGAATTTAATGGAATTACAAACCACAGTGATATAACACACATGCATGAAGATTTCTAACATGCCATCCTAAATTAAGTCACTGTATCAGTCAGAGTCCAAGTATAGGAAACAGTCACTACCCATGCAAACCTGAAGAGACCTTCATACAAGGGAGCTGAGGCAGCCGCAGCCTGCAGCTCTGTCTTCTAGTCTTGCAGGCATTCATTTAGTTAGTGGAAGCATATCTCCTCCCAGAGCCCAGGCTGCAAGAGTCTGAAATGGAGCTTTTAGCTTTCCAGCCTCTGTATCAAAAGGGCACACCAGAAAGAGGCTAGAATGAATGGTTGGGCACTAACAAATATTTTCACAACCTAAGCCCATACTCGCAGTTGTTTGCTGAACAGACAATCAATAAATCAAACAGCCCTTCCATGTAGAAATTAAGAAGGAAACACAACACCAAAACTCATTATTAAATAGCATTTTGTATTTGAAAACTCATTATTAAATAGCAAATAAATTGCACTAAAATACAAAATTGTAGAATTTGTATTCTGGGAAGCCACAGTAACAAATCCCTGTGACAGAACCCACGAAGTAGAGGTCTCCTGTGGGAATGATGACCGAGGCCCTCGCCGCTGCTCCACCTGCCCCTCCAGGGATGCCCTGCTTTTCCAGTTGCCCCTACTCTGATGTGCATCATGGCAGGAAAAAGTGGGCTGCTGCTTTCCTTTAATGCTTTTTGTCCCACTTTATTTTTTACTTTTGCCTAGTATATCTTTTCATTCTTTTATTTTCAACTTTTGTAAATCTCTGTTTTAGGTGGGCTTCTTACGTACAACTTGGAGTTGGGTTTCACTTTTTGATTCAATCTGAAATCTTTTACTTTTACCAACCTTCAGGTTATGTGTATAAAGTTATGTGTTTACATGTATAGATACAATGTTTGGTCTTACTTTTATGACATGTTTTTGTAGCTTTTTGAAAAAGTTTGTGTTCTCTCTGTAGTTCTTCTGAAATTTAGAAATGTTTGCACTATTTTGTACTAGGGGTTACTTTTGGAATTTTAACTCTATGTAATTCCCTCTCCTTCGGAATCCTCATACAACACATCTTAGCCTGTTAGTTTCCTGTTCCACACTGTGATAAAACTGTCATTCATCTTGCTCCTTCTTCCTTCCATCCCTCTCCTCTACAACTTGATTTTAGTGAATAACATCTTACTGCCTCCCTGTGATTATAGGTGAGACAGTCAACAAACCTCTAACCACCGACC', 'position': 1500}, 
    #           {'snpID': 'rs28454925', 'allele': 'G', 'sequence': 'ATCGACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGCAATGGAATCGAATGGGATGGAATGTATTGGAATGGACTCGAATGGCATGGACAGGAGTGGACCCGAATGAAATGGAATGGAATGGAATGGTCTCGAGTGGAATGGGATGGGATGGGATGGGATGCGATGGGATGGGATGGGATGGGATGGGATGGGATGGGATGGATTTGAATGGAATAGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATAGACTCGAAAGGATTGGAATGGAATGGACTCGAATGGAATGGAATGGACATGAATGGAACGGAATGGAATGGAATGAACTCGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATGCAATGGAATGGACTCGAATGGAATGGAATGGAATTGACTCAGATGGAATGGAATGGAATGGACTCGAAAGGATTGGAATGGAATACAATGGAATGGTCTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGACTGCAATGGAATGGACTCAAATGGAATGGAATGGAACTGACTCGAATGGAATTGAATGGAATGGACCCGAATGGAATGGAATGGACTGGGCTCAAATGGAATGGAATGGAAAAGAATGGAATGGAATAGAATGGACTGGAATGTAATGAGTTTGGAATGGACTTGAATGCAATGGAATGGAATGGAATGGAATGGAATGGACTCAAATGGAATAGCATGGAATGGAATGGACTCAAATGCATTGGAATGGAATGGACTCGAATGGAATGGAATGGACTCGAATGGAATGGAGTTGAATGGACTCATATGGAATGGAATGGCATTGAATGGACTCGAATGGAATAGAATTATAACAGAATGGAATGAACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGAAAGGTGCTCGAATAGAATGGAATGGAATGGAATAGAATGGACTCAAATGGAATGGAATATAATGGAATGGGAATGGGAATGGGAATGGAAGGGATGGGATGGGATGGGATGTAATGGAATGGAATGCAATGGAATGGACACCTATGGAATGCAGTTGAATTGAATGGACCCGAAAGCAATGGAATGGAATGCAATGTACTCGAATGGAATGGACTCGAATGGAATGGAATGAACTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAATGGAATGCACCCAAATGGAATTAAATGTAATGGAATGGACTTGAATGAAATGGCAAGAATGGACTCGAATGGAATGGAATGGAATGGAATCGAATGGAATCGAATGGAATGACATGGAATGGATTCGAATGGAAAGACATGGAATGGACTGGATTGGAATGGGTTGGGATGGAATGATCTAGAATGTAATGGAATGGAATGGACTCAAATGGAATAGAATGGAATAGAATGGACTCGAATATAATGGAATGAAATTGGCTCGAATGGAATGGAATGGACTTGAATGGAATGGAATGGAATCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAAAGGAATGGACTCAAATGGAATAGAATTTAATGGAATTACAAACCACAGTGATATAACACACATGCATGAAGATTTCTAACATGCCATCCTAAATTAAGTCACTGTATCAGTCAGAGTCCAAGTATAGGAAACAGTCACTACCCATGCAAACCTGAAGAGACCTTCATACAAGGGAGCTGAGGCAGCCGCAGCCTGCAGCTCTGTCTTCTAGTCTTGCAGGCATTCATTTAGTTAGTGGAAGCATATCTCCTCCCAGAGCCCAGGCTGCAAGAGTCTGAAATGGAGCTTTTAGCTTTCCAGCCTCTGTATCAAAAGGGCACACCAGAAAGAGGCTAGAATGAATGGTTGGGCACTAACAAATATTTTCACAACCTAAGCCCATACTCGCAGTTGTTTGCTGAACAGACAATCAATAAATCAAACAGCCCTTCCATGTAGAAATTAAGAAGGAAACACAACACCAAAACTCATTATTAAATAGCATTTTGTATTTGAAAACTCATTATTAAATAGCAAATAAATTGCACTAAAATACAAAATTGTAGAATTTGTATTCTGGGAAGCCACAGTAACAAATCCCTGTGACAGAACCCACGAAGTAGAGGTCTCCTGTGGGAATGATGACCGAGGCCCTCGCCGCTGCTCCACCTGCCCCTCCAGGGATGCCCTGCTTTTCCAGTTGCCCCTACTCTGATGTGCATCATGGCAGGAAAAAGTGGGCTGCTGCTTTCCTTTAATGCTTTTTGTCCCACTTTATTTTTTACTTTTGCCTAGTATATCTTTTCATTCTTTTATTTTCAACTTTTGTAAATCTCTGTTTTAGGTGGGCTTCTTACGTACAACTTGGAGTTGGGTTTCACTTTTTGATTCAATCTGAAATCTTTTACTTTTACCAACCTTCAGGTTATGTGTATAAAGTTATGTGTTTACATGTATAGATACAATGTTTGGTCTTACTTTTATGACATGTTTTTGTAGCTTTTTGAAAAAGTTTGTGTTCTCTCTGTAGTTCTTCTGAAATTTAGAAATGTTTGCACTATTTTGTACTAGGGGTTACTTTTGGAATTTTAACTCTATGTAATTCCCTCTCCTTCGGAATCCTCATACAACACATCTTAGCCTGTTAGTTTCCTGTTCCACACTGTGATAAAACTGTCATTCATCTTGCTCCTTCTTCCTTCCATCCCTCTCCTCTACAACTTGATTTTAGTGAATAACATCTTACTGCCTCCCTGTGATTATAGGTGAGACAGTCAACAAACCTCTAACCACCGACC', 'position': 1500}, 
    #           {'snpID': 'rs28454925', 'allele': 'T', 'sequence': 'ATCGACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGCAATGGAATCGAATGGGATGGAATGTATTGGAATGGACTCGAATGGCATGGACAGGAGTGGACCCGAATGAAATGGAATGGAATGGAATGGTCTCGAGTGGAATGGGATGGGATGGGATGGGATGCGATGGGATGGGATGGGATGGGATGGGATGGGATGGGATGGATTTGAATGGAATAGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATAGACTCGAAAGGATTGGAATGGAATGGACTCGAATGGAATGGAATGGACATGAATGGAACGGAATGGAATGGAATGAACTCGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATGCAATGGAATGGACTCGAATGGAATGGAATGGAATTGACTCAGATGGAATGGAATGGAATGGACTCGAAAGGATTGGAATGGAATACAATGGAATGGTCTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGACTGCAATGGAATGGACTCAAATGGAATGGAATGGAACTGACTCGAATGGAATTGAATGGAATGGACCCGAATGGAATGGAATGGACTGGGCTCAAATGGAATGGAATGGAAAAGAATGGAATGGAATAGAATGGACTGGAATGTAATGAGTTTGGAATGGACTTGAATGCAATGGAATGGAATGGAATGGAATGGAATGGACTCAAATGGAATAGCATGGAATGGAATGGACTCAAATGCATTGGAATGGAATGGACTCGAATGGAATGGAATGGACTCGAATGGAATGGAGTTGAATGGACTCATATGGAATGGAATGGCATTGAATGGACTCGAATGGAATAGAATTATAACAGAATGGAATGAACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGAAAGGTGCTCGAATAGAATGGAATGGAATGGAATAGAATGGACTCAAATGGAATGGAATATAATGGAATGGGAATGGGAATGGGAATGGAAGGGATGGGATGGGATGGGATGTAATGGAATGGAATGCAATGGAATGGACACCTATGGAATGCAGTTGAATTGAATGGACCCGAAAGCAATGGAATGGAATGCAATGTACTCGAATGGAATGGACTCGAATGGAATGGAATGAACTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAATGGAATGCACCCAAATGGAATTAAATGTAATGGAATGGACTTGAATGAAATGGCAAGAATGGACTCGAATGGAATGGAATGGAATGGAATCGAATGGAATCGAATGGAATGACATGGAATGGATTCGAATGGAAAGACATGGAATGGACTTGATTGGAATGGGTTGGGATGGAATGATCTAGAATGTAATGGAATGGAATGGACTCAAATGGAATAGAATGGAATAGAATGGACTCGAATATAATGGAATGAAATTGGCTCGAATGGAATGGAATGGACTTGAATGGAATGGAATGGAATCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAAAGGAATGGACTCAAATGGAATAGAATTTAATGGAATTACAAACCACAGTGATATAACACACATGCATGAAGATTTCTAACATGCCATCCTAAATTAAGTCACTGTATCAGTCAGAGTCCAAGTATAGGAAACAGTCACTACCCATGCAAACCTGAAGAGACCTTCATACAAGGGAGCTGAGGCAGCCGCAGCCTGCAGCTCTGTCTTCTAGTCTTGCAGGCATTCATTTAGTTAGTGGAAGCATATCTCCTCCCAGAGCCCAGGCTGCAAGAGTCTGAAATGGAGCTTTTAGCTTTCCAGCCTCTGTATCAAAAGGGCACACCAGAAAGAGGCTAGAATGAATGGTTGGGCACTAACAAATATTTTCACAACCTAAGCCCATACTCGCAGTTGTTTGCTGAACAGACAATCAATAAATCAAACAGCCCTTCCATGTAGAAATTAAGAAGGAAACACAACACCAAAACTCATTATTAAATAGCATTTTGTATTTGAAAACTCATTATTAAATAGCAAATAAATTGCACTAAAATACAAAATTGTAGAATTTGTATTCTGGGAAGCCACAGTAACAAATCCCTGTGACAGAACCCACGAAGTAGAGGTCTCCTGTGGGAATGATGACCGAGGCCCTCGCCGCTGCTCCACCTGCCCCTCCAGGGATGCCCTGCTTTTCCAGTTGCCCCTACTCTGATGTGCATCATGGCAGGAAAAAGTGGGCTGCTGCTTTCCTTTAATGCTTTTTGTCCCACTTTATTTTTTACTTTTGCCTAGTATATCTTTTCATTCTTTTATTTTCAACTTTTGTAAATCTCTGTTTTAGGTGGGCTTCTTACGTACAACTTGGAGTTGGGTTTCACTTTTTGATTCAATCTGAAATCTTTTACTTTTACCAACCTTCAGGTTATGTGTATAAAGTTATGTGTTTACATGTATAGATACAATGTTTGGTCTTACTTTTATGACATGTTTTTGTAGCTTTTTGAAAAAGTTTGTGTTCTCTCTGTAGTTCTTCTGAAATTTAGAAATGTTTGCACTATTTTGTACTAGGGGTTACTTTTGGAATTTTAACTCTATGTAATTCCCTCTCCTTCGGAATCCTCATACAACACATCTTAGCCTGTTAGTTTCCTGTTCCACACTGTGATAAAACTGTCATTCATCTTGCTCCTTCTTCCTTCCATCCCTCTCCTCTACAACTTGATTTTAGTGAATAACATCTTACTGCCTCCCTGTGATTATAGGTGAGACAGTCAACAAACCTCTAACCACCGACC', 'position': 1500}]