from Bio.Seq import Seq
import primer3
import re
import json
from Primer_Classes import *
# import numpy as np
# import prc_lib as plib
# snp = 'ATGCAATTGGCCAAATTTGGGCCCAAAATTTTGGGGCCCCAAAAATTTTTGGGGGCCCCCAAAAAATTTTTTGGGGGGCCCCCC'
sequence = 'TTCATGTCCTTCGCCCACTTgTTGATGGGGTTGTTTGTTTT'
# AAAATAACTTCAATT

# c
# TACACAGTACGTGTC
# TTCATGTCCTTCGCCCACTT g TTGATGGGGTTGTTTGTTTT
# TTCATGTCCTTCGCCCACTT G TTGATGGGGTTGTTTGTTTT

snp_df = [{'snpID': 'rs13328683', 'allele': 'G', 'sequence': 'TGT', 'position': 1}, 
 {'snpID': 'rs13328683', 'allele': 'T', 'sequence': 'TTT', 'position': 1}]
# print(snp_df[0]['sequence'][1])
# print(primer3.bindings.calc_hairpin('AAAATAACTTCAATTCTACACAGTACGTGTC'))
# with open('clean_primer_samples.txt', 'w') as output:
#     with open("primer_samples.txt", "r") as input:
#         for line in input:
#             seq = json.loads(line)
#             if re.match(r'^[ATCGatcg]$' ,seq['allele']) and re.match(r'^[ATCGatcg]+$' ,seq['sequence']):
#                 output.write(f"{str(seq)}\n")

min_len = 8
snp_pos = 20
#this gives the shorter half
                            #this gives us the longer half so in case we need to drop a g form the 5' end it balances better
# forward = sequence[snp_pos - (max_len-flank_len) : snp_pos+(flank_len)+1]#this gets the largest segment.   

# reverse = str(Seq(sequence[snp_pos - (flank_len) : snp_pos + (max_len - flank_len + 1)]).reverse_complement())
# reverse2 = str(sequence[snp_pos - (flank_len) : snp_pos + (max_len - flank_len + 1)])
# I want to take a range and for each number make thant flaking length and either end options

len_of_the_flank = (len(sequence)-min_len)//2
for flank in range(len_of_the_flank+1):
    middle_left = sequence[flank:(- flank - 1)]
    middle_right = sequence[flank + 1 :(-flank) if flank != 0 else None]
    middle_middle = sequence[flank:-(flank) if flank != 0 else None]
 

    # print(flank)
    # print(i)
# print(sequence[0:])
# print(flank_len)
# print(forward)
# print(reverse2)
# print(reverse)




    # snp_df = []
    # with open('clean_primer_samples.txt', 'r') as output:
    #     for line in output:
    #         seq = json.loads(line)
    #         snp_df.append(seq)'snpID': 'rs1799971', 'allele': 'G', 'primer_sequence': 'TCAACTTGTCCCACTTAGATGACG', 'direction': 'forward', 'length': 24, 'tm': 60.560716263151505, 'gc_content': 0.4583333333333333, 'hairpin_dg': 0.0, 'homodimer_dg': -2429.733686770949

# jeff = Primer("rs12184297", "T", 'ATTCGAATGGAAAGACATGGAATGGATTC', "forwad")
# kevin = []

# for i in [kevin]:
#     if i:
#         print(i)


# class Dog():
#     def __init__(self, number, name, breed):
#         self.results = number
#         self.name = name
#         self.breed = breed

#     def add_num (self, num):
#         self.results += num

# alfred = Dog(20, "kevin", "shitzhu")
# alfred.add_num(2)
# print(vars(alfred))
# print(alfred.__str__)
# print(alfred.__repr__)
# att = vars(alfred)
# print(att)
# for i in range(10):
#     # print(i)
#     print(f' {i}: {i//2}')


# snp = 'ABCDEFGHIJKLmNOPQRSTUVWXYZ'
# pessimism = 5
# start = 0
# middle = 13
# max_dist = 12
# min_dist = 2
# # for i in range (3):
# #     for length in range(10):
# # trimmed = snp[middle+min_dist:middle+max_dist]
# # print(trimmed)
# # start += 1
# # print("try again")
#     # print(length)
# myString = "Cot"

# print (myString)
# myString = myString[:1] + "A" + myString[2:]
# print (myString)

# snp_data = [{'snpID': 'rs1799971', 'allele': 'A', 'sequence': 'TCCTGGGTCAACTTGTCCCACTTAGATGGCAACCTGTCCGACCCATGCGGTCCGAACCGCA', 'position': 30}, 
#             {'snpID': 'rs1799971', 'allele': 'G', 'sequence': 'TCCTGGGTCAACTTGTCCCACTTAGATGGCGACCTGTCCGACCCATGCGGTCCGAACCGCA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'G', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCGACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'A', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCAACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'C', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCCACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}, 
#             {'snpID': 'rs599839', 'allele': 'T', 'sequence': 'AAAAAAAGAGAAAGAAATAGGAGCAGGATCTACTTCCAGATATACAGAGAATATAAAAATA', 'position': 30}]

# snp_short = snp[0:10]
# print(f"Normal string: {snp_short}")
# seq = Seq.Seq(snp_short)
# print(f"Now a sequence in BIO Python: {seq}")
# reverse = seq.reverse_complement()
# print(f"Now a reverse sequence in Bio Python: {reverse}")
# rev_string = str(reverse)
# print(f"Now a string again: {rev_string}")
# reverse

# np_frame = np.array(snp_data)

# for i in np_frame:
#     print(i['sequence'])
# plib.generate_allele_specific_primers(snp_data, 24, 26)
# test = "TCCTGGGTCAACTTGTCCCACTTANATGGCYACCTGNCCGACCCATGCGGTCCGAACCGCA"
# print(test[30+7:])
# print(test[:30+1-6])# the end is exclusive 
# print(test[-(6+2):-(0)])# the end is exclusive 
# reverse_test = str(Seq(test[30+7:]).reverse_complement())
# print(reverse_test)

# results =
# YACCTGNCCGACCCATGCGGTCCGAACCGCA
# TCCTGGGTCAACTTGTCCCACTTANATGGCY

# CCGACCCATGCGGTCCGAACCGCA
# TGCGGTTCGGACCGCATGGGTCGG
# inverted and spun around
# {'snpID': 'rs2977670', 'allele': 'T', 'primer_sequence': 'GGACCTATTGCTTAAGGTGGGT', 'direction': 'forward', 'length': 22, 'tm': 59.758569657346015, 'gc_content': 0.5, 
# 'hairpin': ThermoResult(structure_found=True, tm=46.22, dg=-739.31, dh=-25600.00, ds=-80.16), 'homomdimer': ThermoResult(structure_found=True, tm=4.29, dg=-4565.16, dh=-56400.00, ds=-167.13), 'tm_score': 0.24143034265398455, 'gc_score': 49.5, 'score': 49.741430342653985}

# {'snpID': 'rs2977670', 'allele': 'T', 'primer_sequence': 'TTCCGTTCTATTCCATTCTAGTCC', 'direction': 'forward', 'length': 24, 'tm': 57.84197746874719, 'gc_content': 0.4166666666666667, 'hairpin': ThermoResult(structure_found=False, tm=0.00, dg=0.00, dh=0.00, ds=0.00), 'homomdimer': ThermoResult(structure_found=True, tm=-19.22, dg=-2493.09, dh=-39400.00, ds=-119.00), 'tm_score': 2.1580225312528114, 'gc_score': 49.583333333333336, 'score': 51.74135586458615}


# snp_df = [{'snpID': 'rs28454925', 'allele': 'C', 'sequence': 'ATCGACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGCAATGGAATCGAATGGGATGGAATGTATTGGAATGGACTCGAATGGCATGGACAGGAGTGGACCCGAATGAAATGGAATGGAATGGAATGGTCTCGAGTGGAATGGGATGGGATGGGATGGGATGCGATGGGATGGGATGGGATGGGATGGGATGGGATGGGATGGATTTGAATGGAATAGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATAGACTCGAAAGGATTGGAATGGAATGGACTCGAATGGAATGGAATGGACATGAATGGAACGGAATGGAATGGAATGAACTCGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATGCAATGGAATGGACTCGAATGGAATGGAATGGAATTGACTCAGATGGAATGGAATGGAATGGACTCGAAAGGATTGGAATGGAATACAATGGAATGGTCTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGACTGCAATGGAATGGACTCAAATGGAATGGAATGGAACTGACTCGAATGGAATTGAATGGAATGGACCCGAATGGAATGGAATGGACTGGGCTCAAATGGAATGGAATGGAAAAGAATGGAATGGAATAGAATGGACTGGAATGTAATGAGTTTGGAATGGACTTGAATGCAATGGAATGGAATGGAATGGAATGGAATGGACTCAAATGGAATAGCATGGAATGGAATGGACTCAAATGCATTGGAATGGAATGGACTCGAATGGAATGGAATGGACTCGAATGGAATGGAGTTGAATGGACTCATATGGAATGGAATGGCATTGAATGGACTCGAATGGAATAGAATTATAACAGAATGGAATGAACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGAAAGGTGCTCGAATAGAATGGAATGGAATGGAATAGAATGGACTCAAATGGAATGGAATATAATGGAATGGGAATGGGAATGGGAATGGAAGGGATGGGATGGGATGGGATGTAATGGAATGGAATGCAATGGAATGGACACCTATGGAATGCAGTTGAATTGAATGGACCCGAAAGCAATGGAATGGAATGCAATGTACTCGAATGGAATGGACTCGAATGGAATGGAATGAACTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAATGGAATGCACCCAAATGGAATTAAATGTAATGGAATGGACTTGAATGAAATGGCAAGAATGGACTCGAATGGAATGGAATGGAATGGAATCGAATGGAATCGAATGGAATGACATGGAATGGATTCGAATGGAAAGACATGGAATGGACTCGATTGGAATGGGTTGGGATGGAATGATCTAGAATGTAATGGAATGGAATGGACTCAAATGGAATAGAATGGAATAGAATGGACTCGAATATAATGGAATGAAATTGGCTCGAATGGAATGGAATGGACTTGAATGGAATGGAATGGAATCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAAAGGAATGGACTCAAATGGAATAGAATTTAATGGAATTACAAACCACAGTGATATAACACACATGCATGAAGATTTCTAACATGCCATCCTAAATTAAGTCACTGTATCAGTCAGAGTCCAAGTATAGGAAACAGTCACTACCCATGCAAACCTGAAGAGACCTTCATACAAGGGAGCTGAGGCAGCCGCAGCCTGCAGCTCTGTCTTCTAGTCTTGCAGGCATTCATTTAGTTAGTGGAAGCATATCTCCTCCCAGAGCCCAGGCTGCAAGAGTCTGAAATGGAGCTTTTAGCTTTCCAGCCTCTGTATCAAAAGGGCACACCAGAAAGAGGCTAGAATGAATGGTTGGGCACTAACAAATATTTTCACAACCTAAGCCCATACTCGCAGTTGTTTGCTGAACAGACAATCAATAAATCAAACAGCCCTTCCATGTAGAAATTAAGAAGGAAACACAACACCAAAACTCATTATTAAATAGCATTTTGTATTTGAAAACTCATTATTAAATAGCAAATAAATTGCACTAAAATACAAAATTGTAGAATTTGTATTCTGGGAAGCCACAGTAACAAATCCCTGTGACAGAACCCACGAAGTAGAGGTCTCCTGTGGGAATGATGACCGAGGCCCTCGCCGCTGCTCCACCTGCCCCTCCAGGGATGCCCTGCTTTTCCAGTTGCCCCTACTCTGATGTGCATCATGGCAGGAAAAAGTGGGCTGCTGCTTTCCTTTAATGCTTTTTGTCCCACTTTATTTTTTACTTTTGCCTAGTATATCTTTTCATTCTTTTATTTTCAACTTTTGTAAATCTCTGTTTTAGGTGGGCTTCTTACGTACAACTTGGAGTTGGGTTTCACTTTTTGATTCAATCTGAAATCTTTTACTTTTACCAACCTTCAGGTTATGTGTATAAAGTTATGTGTTTACATGTATAGATACAATGTTTGGTCTTACTTTTATGACATGTTTTTGTAGCTTTTTGAAAAAGTTTGTGTTCTCTCTGTAGTTCTTCTGAAATTTAGAAATGTTTGCACTATTTTGTACTAGGGGTTACTTTTGGAATTTTAACTCTATGTAATTCCCTCTCCTTCGGAATCCTCATACAACACATCTTAGCCTGTTAGTTTCCTGTTCCACACTGTGATAAAACTGTCATTCATCTTGCTCCTTCTTCCTTCCATCCCTCTCCTCTACAACTTGATTTTAGTGAATAACATCTTACTGCCTCCCTGTGATTATAGGTGAGACAGTCAACAAACCTCTAACCACCGACC', 'position': 1500}, 
    #           {'snpID': 'rs28454925', 'allele': 'G', 'sequence': 'ATCGACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGCAATGGAATCGAATGGGATGGAATGTATTGGAATGGACTCGAATGGCATGGACAGGAGTGGACCCGAATGAAATGGAATGGAATGGAATGGTCTCGAGTGGAATGGGATGGGATGGGATGGGATGCGATGGGATGGGATGGGATGGGATGGGATGGGATGGGATGGATTTGAATGGAATAGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATAGACTCGAAAGGATTGGAATGGAATGGACTCGAATGGAATGGAATGGACATGAATGGAACGGAATGGAATGGAATGAACTCGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATGCAATGGAATGGACTCGAATGGAATGGAATGGAATTGACTCAGATGGAATGGAATGGAATGGACTCGAAAGGATTGGAATGGAATACAATGGAATGGTCTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGACTGCAATGGAATGGACTCAAATGGAATGGAATGGAACTGACTCGAATGGAATTGAATGGAATGGACCCGAATGGAATGGAATGGACTGGGCTCAAATGGAATGGAATGGAAAAGAATGGAATGGAATAGAATGGACTGGAATGTAATGAGTTTGGAATGGACTTGAATGCAATGGAATGGAATGGAATGGAATGGAATGGACTCAAATGGAATAGCATGGAATGGAATGGACTCAAATGCATTGGAATGGAATGGACTCGAATGGAATGGAATGGACTCGAATGGAATGGAGTTGAATGGACTCATATGGAATGGAATGGCATTGAATGGACTCGAATGGAATAGAATTATAACAGAATGGAATGAACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGAAAGGTGCTCGAATAGAATGGAATGGAATGGAATAGAATGGACTCAAATGGAATGGAATATAATGGAATGGGAATGGGAATGGGAATGGAAGGGATGGGATGGGATGGGATGTAATGGAATGGAATGCAATGGAATGGACACCTATGGAATGCAGTTGAATTGAATGGACCCGAAAGCAATGGAATGGAATGCAATGTACTCGAATGGAATGGACTCGAATGGAATGGAATGAACTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAATGGAATGCACCCAAATGGAATTAAATGTAATGGAATGGACTTGAATGAAATGGCAAGAATGGACTCGAATGGAATGGAATGGAATGGAATCGAATGGAATCGAATGGAATGACATGGAATGGATTCGAATGGAAAGACATGGAATGGACTGGATTGGAATGGGTTGGGATGGAATGATCTAGAATGTAATGGAATGGAATGGACTCAAATGGAATAGAATGGAATAGAATGGACTCGAATATAATGGAATGAAATTGGCTCGAATGGAATGGAATGGACTTGAATGGAATGGAATGGAATCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAAAGGAATGGACTCAAATGGAATAGAATTTAATGGAATTACAAACCACAGTGATATAACACACATGCATGAAGATTTCTAACATGCCATCCTAAATTAAGTCACTGTATCAGTCAGAGTCCAAGTATAGGAAACAGTCACTACCCATGCAAACCTGAAGAGACCTTCATACAAGGGAGCTGAGGCAGCCGCAGCCTGCAGCTCTGTCTTCTAGTCTTGCAGGCATTCATTTAGTTAGTGGAAGCATATCTCCTCCCAGAGCCCAGGCTGCAAGAGTCTGAAATGGAGCTTTTAGCTTTCCAGCCTCTGTATCAAAAGGGCACACCAGAAAGAGGCTAGAATGAATGGTTGGGCACTAACAAATATTTTCACAACCTAAGCCCATACTCGCAGTTGTTTGCTGAACAGACAATCAATAAATCAAACAGCCCTTCCATGTAGAAATTAAGAAGGAAACACAACACCAAAACTCATTATTAAATAGCATTTTGTATTTGAAAACTCATTATTAAATAGCAAATAAATTGCACTAAAATACAAAATTGTAGAATTTGTATTCTGGGAAGCCACAGTAACAAATCCCTGTGACAGAACCCACGAAGTAGAGGTCTCCTGTGGGAATGATGACCGAGGCCCTCGCCGCTGCTCCACCTGCCCCTCCAGGGATGCCCTGCTTTTCCAGTTGCCCCTACTCTGATGTGCATCATGGCAGGAAAAAGTGGGCTGCTGCTTTCCTTTAATGCTTTTTGTCCCACTTTATTTTTTACTTTTGCCTAGTATATCTTTTCATTCTTTTATTTTCAACTTTTGTAAATCTCTGTTTTAGGTGGGCTTCTTACGTACAACTTGGAGTTGGGTTTCACTTTTTGATTCAATCTGAAATCTTTTACTTTTACCAACCTTCAGGTTATGTGTATAAAGTTATGTGTTTACATGTATAGATACAATGTTTGGTCTTACTTTTATGACATGTTTTTGTAGCTTTTTGAAAAAGTTTGTGTTCTCTCTGTAGTTCTTCTGAAATTTAGAAATGTTTGCACTATTTTGTACTAGGGGTTACTTTTGGAATTTTAACTCTATGTAATTCCCTCTCCTTCGGAATCCTCATACAACACATCTTAGCCTGTTAGTTTCCTGTTCCACACTGTGATAAAACTGTCATTCATCTTGCTCCTTCTTCCTTCCATCCCTCTCCTCTACAACTTGATTTTAGTGAATAACATCTTACTGCCTCCCTGTGATTATAGGTGAGACAGTCAACAAACCTCTAACCACCGACC', 'position': 1500}, 
    #           {'snpID': 'rs28454925', 'allele': 'T', 'sequence': 'ATCGACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGCAATGGAATCGAATGGGATGGAATGTATTGGAATGGACTCGAATGGCATGGACAGGAGTGGACCCGAATGAAATGGAATGGAATGGAATGGTCTCGAGTGGAATGGGATGGGATGGGATGGGATGCGATGGGATGGGATGGGATGGGATGGGATGGGATGGGATGGATTTGAATGGAATAGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATAGACTCGAAAGGATTGGAATGGAATGGACTCGAATGGAATGGAATGGACATGAATGGAACGGAATGGAATGGAATGAACTCGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATACAATGGAATTTAATGGAATGGACTCTAATGGAATGGACTTGAATGGAATAGAATGGAAGAGACTCGAATGGAATGGAATGCAATGGAATGGACTCGAATGGAATGGAATGGAATTGACTCAGATGGAATGGAATGGAATGGACTCGAAAGGATTGGAATGGAATACAATGGAATGGTCTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGACTGCAATGGAATGGACTCAAATGGAATGGAATGGAACTGACTCGAATGGAATTGAATGGAATGGACCCGAATGGAATGGAATGGACTGGGCTCAAATGGAATGGAATGGAAAAGAATGGAATGGAATAGAATGGACTGGAATGTAATGAGTTTGGAATGGACTTGAATGCAATGGAATGGAATGGAATGGAATGGAATGGACTCAAATGGAATAGCATGGAATGGAATGGACTCAAATGCATTGGAATGGAATGGACTCGAATGGAATGGAATGGACTCGAATGGAATGGAGTTGAATGGACTCATATGGAATGGAATGGCATTGAATGGACTCGAATGGAATAGAATTATAACAGAATGGAATGAACCCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGAAAGGTGCTCGAATAGAATGGAATGGAATGGAATAGAATGGACTCAAATGGAATGGAATATAATGGAATGGGAATGGGAATGGGAATGGAAGGGATGGGATGGGATGGGATGTAATGGAATGGAATGCAATGGAATGGACACCTATGGAATGCAGTTGAATTGAATGGACCCGAAAGCAATGGAATGGAATGCAATGTACTCGAATGGAATGGACTCGAATGGAATGGAATGAACTCGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAATGGAATGCACCCAAATGGAATTAAATGTAATGGAATGGACTTGAATGAAATGGCAAGAATGGACTCGAATGGAATGGAATGGAATGGAATCGAATGGAATCGAATGGAATGACATGGAATGGATTCGAATGGAAAGACATGGAATGGACTTGATTGGAATGGGTTGGGATGGAATGATCTAGAATGTAATGGAATGGAATGGACTCAAATGGAATAGAATGGAATAGAATGGACTCGAATATAATGGAATGAAATTGGCTCGAATGGAATGGAATGGACTTGAATGGAATGGAATGGAATCGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGAATGGACTCGAATGGAATGGAAAGGAATGGACTCAAATGGAATAGAATTTAATGGAATTACAAACCACAGTGATATAACACACATGCATGAAGATTTCTAACATGCCATCCTAAATTAAGTCACTGTATCAGTCAGAGTCCAAGTATAGGAAACAGTCACTACCCATGCAAACCTGAAGAGACCTTCATACAAGGGAGCTGAGGCAGCCGCAGCCTGCAGCTCTGTCTTCTAGTCTTGCAGGCATTCATTTAGTTAGTGGAAGCATATCTCCTCCCAGAGCCCAGGCTGCAAGAGTCTGAAATGGAGCTTTTAGCTTTCCAGCCTCTGTATCAAAAGGGCACACCAGAAAGAGGCTAGAATGAATGGTTGGGCACTAACAAATATTTTCACAACCTAAGCCCATACTCGCAGTTGTTTGCTGAACAGACAATCAATAAATCAAACAGCCCTTCCATGTAGAAATTAAGAAGGAAACACAACACCAAAACTCATTATTAAATAGCATTTTGTATTTGAAAACTCATTATTAAATAGCAAATAAATTGCACTAAAATACAAAATTGTAGAATTTGTATTCTGGGAAGCCACAGTAACAAATCCCTGTGACAGAACCCACGAAGTAGAGGTCTCCTGTGGGAATGATGACCGAGGCCCTCGCCGCTGCTCCACCTGCCCCTCCAGGGATGCCCTGCTTTTCCAGTTGCCCCTACTCTGATGTGCATCATGGCAGGAAAAAGTGGGCTGCTGCTTTCCTTTAATGCTTTTTGTCCCACTTTATTTTTTACTTTTGCCTAGTATATCTTTTCATTCTTTTATTTTCAACTTTTGTAAATCTCTGTTTTAGGTGGGCTTCTTACGTACAACTTGGAGTTGGGTTTCACTTTTTGATTCAATCTGAAATCTTTTACTTTTACCAACCTTCAGGTTATGTGTATAAAGTTATGTGTTTACATGTATAGATACAATGTTTGGTCTTACTTTTATGACATGTTTTTGTAGCTTTTTGAAAAAGTTTGTGTTCTCTCTGTAGTTCTTCTGAAATTTAGAAATGTTTGCACTATTTTGTACTAGGGGTTACTTTTGGAATTTTAACTCTATGTAATTCCCTCTCCTTCGGAATCCTCATACAACACATCTTAGCCTGTTAGTTTCCTGTTCCACACTGTGATAAAACTGTCATTCATCTTGCTCCTTCTTCCTTCCATCCCTCTCCTCTACAACTTGATTTTAGTGAATAACATCTTACTGCCTCCCTGTGATTATAGGTGAGACAGTCAACAAACCTCTAACCACCGACC', 'position': 1500}]